### ISSUE TITLE
Check parsing

### ISSUE THREAD

**Issue by 0x0584** [bauom/Lem-in#3]
## About

Efficient parsing of multiple graph, with big number of nodes and edges, with no memory leaks nor errors.

**Comment by bauom** [comment]
fixed error that was occurring if the file started with comment

**Comment by bauom** [comment]
need to fix another bug to check the edges names

**Comment by 0x0584** [comment]
Since the graph used to create the flow network is undirected, eliminate edge `a-b` if edge `b-a` occurs.

**Comment by bauom** [comment]
> Since the graph used to create the flow network is undirected, eliminate edge `a-b` if edge `b-a` occurs.

i am trying to fix it without taking to much to process

**Comment by 0x0584** [comment]
> > Since the graph used to create the flow network is undirected, eliminate edge `a-b` if edge `b-a` occurs.
> 
> i am trying to fix it without taking to much to process

It seems like using a hash table to store edges, add only unique source node names would do the job..

**Comment by 0x0584** [comment]
Added some extra maps on #11, some of them are **not working**!
